version: "3.8"

services:
  user-api-service:
    build: ./services/user-api-service
    ports:
      - "5001:5001"
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/GridStackUser
    networks:
      - grindstack-net

  product-api-service:
    build: ./services/product-catalog-api-service
    ports:
      - "5002:5002"
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo:27017/GridStackProductsCatalog
    networks:
      - grindstack-net

  cart-api-service:
    build: ./services/cart-api-service
    ports:
      - "5004:5004"
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/GridStackCart
      - PRODUCT_API_URL=http://product-api-service:5002/products
      - ORDER_API_URL=http://order-api-service:5003/orders
    networks:
      - grindstack-net

  order-api-service:
    build: ./services/order-api-service
    ports:
      - "5003:5003"
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo:27017/GridStackOrders
    networks:
      - grindstack-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - grindstack-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: junedelmar
      RABBITMQ_DEFAULT_PASS: junedelmar
    restart: unless-stopped
    networks:
      - grindstack-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - user-api-service
      - product-api-service
      - cart-api-service
      - order-api-service
    networks:
      - grindstack-net

volumes:
  mongo-data:

networks:
  grindstack-net:
    driver: bridge
